services:
  nginx:
    build: /home/deb/srcs/requirements/nginx/.
    container_name: nginx
    ports:
      - "80:80"
    volumes:
    - ./web:/var/www/html
  wordpress:
    build: /home/deb/srcs/requirements/wordpress/.
    container_name: wp-php
    volumes:
    - ./web:/var/www/html