
services:
  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - /home/zachamou/data/var/lib/mysql/web:/var/www/html
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress/.
    container_name: wp-php
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    volumes:
      - /home/zachamou/data/var/lib/mysql/web:/var/www/html
    env_file:
    - /home/deb/work_lab/env/.env
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    volumes:
      - /home/zachamou/data/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - /home/deb/work_lab/env/.env
    networks:
      - inception

networks:
  inception: {}

volumes:
  mariadb_data:
